name: CI Checks

on:
  push:
    branches:
      - dev
      - feature/**
  pull_request:
    branches:
      - dev

jobs:
  ci:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint code
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build package
        run: yarn build

      - name: Check types
        run: yarn tsc --noEmit

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/